---
on: workflow_dispatch

jobs:
  build-vms:
    uses: ./.github/workflows/build-vm.yml
    with:
      buildRepo: Nuttymoon/subnet-evm
      buildCommand: ./scripts/build.sh ./build/subnetevm-{0}/subnetevm
      buildTag: v0.1.2
