---
on:
  workflow_call:
    inputs:
      buildRepo:
        required: true
        type: string
      buildCommand:
        required: true
        type: string
      buildTag:
        required: true
        type: string

jobs:
  build-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout VM repository
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.buildRepo }}
          path: ${{ inputs.buildRepo }}
          ref: ${{ inputs.buildTag }}

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.16.8"
          check-latest: true

      - name: Build VM
        run: ${{ format(inputs.buildCommand, inputs.buildTag) }}
        working-directory: ${{ inputs.buildRepo }}
