---
on:

jobs:
  build-vm:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/build.yml
        with:
          build-repo: https://github.com/Nuttymoon/subnet-evm
          build-command: ./build/subnetevm-v0.1.2/subnetevm
