---
on:
  workflow_call:
    inputs:
      vmName:
        required: true
        type: string
      vmRepo:
        required: true
        type: string
      buildCommand:
        required: true
        type: string
      buildTag:
        required: true
        type: string
      buildArchive:
        required: true
        type: string

jobs:
  build-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout VM repository
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.vmRepo }}
          path: ${{ inputs.vmRepo }}
          ref: ${{ inputs.buildTag }}

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.16.8"
          check-latest: true

      - name: Build VM
        run: ${{ format(inputs.buildCommand, inputs.vmName, inputs.buildTag) }}
        working-directory: ${{ inputs.vmRepo }}

      - name: Compress VM binary to tar.gz
        run: |
          tar -czf ./${{ format(inputs.buildArchive, inputs.vmName, inputs.buildTag) }} \
            ./${{ inputs.vmName }}-${{ inputs.buildTag }}
        working-directory: ${{ inputs.vmRepo }}/build
