---
on: workflow_dispatch

jobs:
  build-vm:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/build.yml
        with:
          buildRepo: https://github.com/Nuttymoon/subnet-evm
          buildCommand: ./build/subnetevm-v0.1.2/subnetevm
