---
on:
  workflow_call:
    inputs:
      buildRepo:
        required: true
        type: string
      buildCommand:
        required: true
        type: string

jobs:
  build-vm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.buildRepo }}
          # path: ${{ inputs.buildRepo }}
