---
name: Sync and build releases of Avalanche VMs forks

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sync-build-timestampvm:
    uses: ./.github/workflows/sync-forked-vm.yml
    with:
      vmName: timestampvm
      vmForkRepo: Nuttymoon/timestampvm
      vmSourceRepo: ava-labs/timestampvm
      buildCommand: "./scripts/build.sh ./build/{0}-{1} {0}"
      buildArchive: "{0}-linux-amd64-{1}.tar.gz"
    secrets:
      githubPat: ${{ secrets.NUTTYMOON_PAT }}

  sync-build-spacesvm:
    uses: ./.github/workflows/sync-forked-vm.yml
    with:
      vmName: spacesvm
      vmForkRepo: Nuttymoon/spacesvm
      vmSourceRepo: ava-labs/spacesvm
      buildCommand: |
        ./scripts/build.sh
        mkdir ./build/{0}-{1}
        mv ./build/sqja3uK17MJxfC7AN8nGadBw9JK5BcrsNwNynsqP5Gih8M5Bm ./build/{0}-{1}/{0}
      buildArchive: "{0}-linux-amd64-{1}.tar.gz"
    secrets:
      githubPat: ${{ secrets.NUTTYMOON_PAT }}

  sync-build-subnetevm:
    uses: ./.github/workflows/sync-forked-vm.yml
    with:
      vmName: subnetevm
      vmForkRepo: Nuttymoon/subnet-evm
      vmSourceRepo: ava-labs/subnet-evm
      buildCommand: "./scripts/build.sh ./build/{0}-{1}/{0}"
      buildArchive: "{0}-linux-amd64-{1}.tar.gz"
    secrets:
      githubPat: ${{ secrets.NUTTYMOON_PAT }}
