---
name: Sync and build releases of Avalanche VMs forks

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sync-build-blobvm:
    uses: ./.github/workflows/sync-forked-vm.yml
    with:
      vmName: blobvm
      vmForkRepo: AshAvalanche/blobvm
      vmSourceRepo: ava-labs/blobvm
      buildCommand: |
        ./scripts/build.sh
        mkdir ./build/{0}-{1}
        vm_id=$(cat scripts/build.sh | grep -oP '(kM6h4LYe3AcEU1MB2UNg6ubzAiDAALZzpVrbX8zn3hXF6Avd8|sqja3uK17MJxfC7AN8nGadBw9JK5BcrsNwNynsqP5Gih8M5Bm)')
        mv "./build/$vm_id" ./build/{0}-{1}/{0}
      buildArchive: "{0}-linux-amd64-{1}.tar.gz"
    secrets:
      githubPat: ${{ secrets.ASHAVALANCHEBOT_PAT }}

  sync-build-timestampvm:
    uses: ./.github/workflows/sync-forked-vm.yml
    with:
      vmName: timestampvm
      vmForkRepo: AshAvalanche/timestampvm
      vmSourceRepo: ava-labs/timestampvm
      buildCommand: "./scripts/build.sh ./build/{0}-{1} {0}"
      buildArchive: "{0}-linux-amd64-{1}.tar.gz"
    secrets:
      githubPat: ${{ secrets.ASHAVALANCHEBOT_PAT }}

  sync-build-spacesvm:
    uses: ./.github/workflows/sync-forked-vm.yml
    with:
      vmName: spacesvm
      vmForkRepo: AshAvalanche/spacesvm
      vmSourceRepo: ava-labs/spacesvm
      buildCommand: |
        ./scripts/build.sh
        mkdir ./build/{0}-{1}
        mv ./build/sqja3uK17MJxfC7AN8nGadBw9JK5BcrsNwNynsqP5Gih8M5Bm ./build/{0}-{1}/{0}
      buildArchive: "{0}-linux-amd64-{1}.tar.gz"
    secrets:
      githubPat: ${{ secrets.ASHAVALANCHEBOT_PAT }}

  sync-build-subnetevm:
    uses: ./.github/workflows/sync-forked-vm.yml
    with:
      vmName: subnetevm
      vmForkRepo: AshAvalanche/subnet-evm
      vmSourceRepo: ava-labs/subnet-evm
      buildCommand: |
        ./scripts/build.sh ./build/srEXiWaHuhNyGwPUi444Tu47ZEDwxTWrbQiuD7FmgSAQ6X7Dy
        mkdir ./build/{0}-{1}
        mv build/srEXiWaHuhNyGwPUi444Tu47ZEDwxTWrbQiuD7FmgSAQ6X7Dy build/{0}-{1}/{0}
      buildArchive: "{0}-linux-amd64-{1}.tar.gz"
    secrets:
      githubPat: ${{ secrets.ASHAVALANCHEBOT_PAT }}
